name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to release'
        required: true
        type: choice
        options:
          - '@outscope/orpc-hono'
          - '@outscope/cli'
          - 'both'
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm --filter @outscope/orpc-hono test && pnpm --filter @outscope/cli test

      - name: Type check packages
        run: pnpm --filter @outscope/orpc-hono check-types && pnpm --filter @outscope/cli check-types

      - name: Build packages
        run: pnpm --filter @outscope/orpc-hono build && pnpm --filter @outscope/cli build

      - name: Create changeset for selected package
        if: github.event_name == 'workflow_dispatch'
        run: |
          PACKAGE="${{ github.event.inputs.package }}"
          VERSION_TYPE="${{ github.event.inputs.version_type }}"

          if [ "$PACKAGE" = "both" ]; then
            cat <<EOF > .changeset/release-both.md
          ---
          "@outscope/orpc-hono": $VERSION_TYPE
          "@outscope/cli": $VERSION_TYPE
          ---

          Release $VERSION_TYPE version for both packages
          EOF
          elif [ "$PACKAGE" = "@outscope/orpc-hono" ]; then
            cat <<EOF > .changeset/release-orpc-hono.md
          ---
          "@outscope/orpc-hono": $VERSION_TYPE
          ---

          Release $VERSION_TYPE version for @outscope/orpc-hono
          EOF
          else
            cat <<EOF > .changeset/release-cli.md
          ---
          "@outscope/cli": $VERSION_TYPE
          ---

          Release $VERSION_TYPE version for @outscope/cli
          EOF
          fi

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Summary
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "## 🚀 Packages Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The following packages were published:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -r '.[] | "- **\(.name)@\(.version)**"' >> $GITHUB_STEP_SUMMARY
